version: '3.8'

services:
  inference-api:
    build: .
    container_name: fast_inference_api
    ports:
      - "8000:8000"
    volumes:
      # Syncs your local 'app' folder to the container
      # This allows you to edit code in VS Code and see changes instantly without rebuilding
      - ./app:/app/app
      - ./models:/app/models
    environment:
      - APP_ENV=development
    # restart: always  <-- Uncomment this for production
